// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/content.ts
var profile = {
  name: "John Min",
  location: "San Francisco, CA (37.7749\xB0 N, 122.4194\xB0 W)",
  tagline: "A collection of projects, ideas, and explorations at the intersection of design, technology, and culture."
};
var background = {
  education: "Duke undergrad (economics, math, public policy) \u2192 Columbia grad (statistics, ML).",
  experience: [
    "Data science across fintech, healthcare, advertising, politics, media, and web3.",
    "Product and strategy in consumer credit, emerging markets lending, and digital transformation."
  ],
  dignifi: "Co-founded Dignifi \u2014 AI-powered reentry support for justice-impacted individuals across housing, health, and employment.",
  currentInterests: [
    "AI systems, fintech, stablecoins, agentic commerce, and the automation of everything that moves.",
    "House music, tennis, writing, and visual art performance."
  ]
};
var links = [
  { label: "Substack", url: "https://johnmin.substack.com" },
  { label: "LinkedIn", url: "https://www.linkedin.com/in/johncmin" },
  { label: "Twitter / X", url: "https://x.com/heyjohnmin" },
  { label: "GitHub", url: "https://github.com/john-min" }
];
var projects = [
  {
    title: "StreamEngine",
    description: "Stablecoin payout orchestration, treasury operations, and reconciliation for businesses and autonomous agents.",
    tags: ["Fintech", "Operations", "Agents"],
    status: "Sandbox prototype",
    url: "https://stream-engine-pi.vercel.app",
    group: "Financial systems",
    accent: "secondary"
  },
  {
    title: "Wireframe",
    description: "A minimal consumer wallet for sending digital dollars across Base and Tempo.",
    tags: ["Stablecoins", "Wallets", "Consumer"],
    status: "Live prototype",
    url: "https://wireframe-stablecoin.vercel.app",
    group: "Financial systems",
    accent: "secondary",
    note: "Opens directly into authentication \u2014 a public walkthrough is in progress."
  },
  {
    title: "Cardiac Beats",
    description: "An EKG-inspired drum sequencer and rhythm visualizer.",
    tags: ["Music", "Interaction"],
    status: "Live",
    url: "https://cardiac-beats.vercel.app",
    group: "Music experiments",
    accent: "primary"
  },
  {
    title: "Synth Matrix",
    description: "An AI guide that matches musical taste with iconic synthesizers.",
    tags: ["AI", "Music"],
    status: "Live",
    url: "https://synth-matrix.vercel.app",
    group: "Music experiments",
    accent: "accent"
  },
  {
    title: "Crate Dig",
    description: "Visual music discovery that maps a DJ's library by sound.",
    tags: ["Music", "AI", "Discovery"],
    status: "Live",
    url: "https://cratedig.forbiddenfruitsound.com",
    group: "Music experiments",
    accent: "primary"
  }
];

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get John Min's name, location, and short site tagline from johnmin.xyz.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
    structuredContent: profile
  })
});

// src/lib/mcp/tools/get-background.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_background_default = defineTool2({
  name: "get_background",
  title: "Get background",
  description: "Get John Min's education, professional experience, Dignifi work, and current interests.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(background, null, 2) }],
    structuredContent: background
  })
});

// src/lib/mcp/tools/list-links.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_links_default = defineTool3({
  name: "list_links",
  title: "List links",
  description: "List John Min's public profile links (Substack, LinkedIn, X, GitHub).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(links, null, 2) }],
    structuredContent: { links }
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List projects",
  description: "List John Min's projects and experiments, including title, description, tags, status, and live URL.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(projects, null, 2)
      }
    ],
    structuredContent: { projects }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "johnmin-xyz",
  title: "johnmin.xyz",
  version: "0.1.0",
  instructions: "Public tools for johnmin.xyz, the personal site of John Min. Use `get_profile` for name, location, and tagline; `get_background` for education, experience, and current interests; `list_links` for public profile links; `list_projects` for published work.",
  auth: auth.oauth.issuer({
    issuer: "https://bzwkqbtongqvqbdyyuhh.supabase.co/auth/v1",
    resource: "https://bzwkqbtongqvqbdyyuhh.supabase.co/functions/v1/mcp",
    acceptedAudiences: ["authenticated"],
    resourceName: "johnmin.xyz MCP"
  }),
  tools: [get_profile_default, get_background_default, list_links_default, list_projects_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
